// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
)

const (
	OidcScopes = "oidc.Scopes"
)

// Group A group / role for a User
type Group = string

// ID UUID
type ID = string

// User Resprentation of a User.
type User struct {
	Address      *string  `json:"address,omitempty"`
	Birthday     *float32 `json:"birthday,omitempty"`
	Blog         *string  `json:"blog,omitempty"`
	Callsign     *string  `json:"callsign,omitempty"`
	ClassYear    *int     `json:"class_year,omitempty"`
	Codeberg     *string  `json:"codeberg,omitempty"`
	DisplayName  *string  `json:"display_name,omitempty"`
	DrinkBalance *int     `json:"drink_balance,omitempty"`

	// Email Otherwise known as UPN in Microsoft-land
	Email         *string   `json:"email,omitempty"`
	Emails        *[]string `json:"emails,omitempty"`
	FirstName     *string   `json:"first_name,omitempty"`
	Github        *string   `json:"github,omitempty"`
	Groups        *[]Group  `json:"groups,omitempty"`
	HomeDirectory *string   `json:"home_directory,omitempty"`
	HousingPoints *int      `json:"housing_points,omitempty"`
	LastName      *string   `json:"last_name,omitempty"`
	LoginShell    *string   `json:"login_shell,omitempty"`
	Major         *string   `json:"major,omitempty"`
	MemberSince   *string   `json:"member_since,omitempty"`
	Minor         *string   `json:"minor,omitempty"`
	PhoneNumber   *[]string `json:"phone_number,omitempty"`
	Plex          *string   `json:"plex,omitempty"`
	Pronouns      *string   `json:"pronouns,omitempty"`
	PublicKeys    *[]string `json:"public_keys,omitempty"`
	ResumeUrl     *string   `json:"resume_url,omitempty"`
	RitUsername   *string   `json:"rit_username,omitempty"`
	RoomNumber    *int      `json:"room_number,omitempty"`
	SlackUid      *string   `json:"slack_uid,omitempty"`
	Twitter       *string   `json:"twitter,omitempty"`

	// UserId UUID
	UserId   *ID     `json:"user_id,omitempty"`
	Username *string `json:"username,omitempty"`
	Website  *string `json:"website,omitempty"`
}

// GetUserParams defines parameters for GetUser.
type GetUserParams struct {
	// Fields Get fields outside the default fields. May require additional OIDC scopes.
	Fields *[]string `form:"fields,omitempty" json:"fields,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List users
	// (GET /api/v1/users)
	GetUsers(c *gin.Context)
	// Returns a user by ID
	// (GET /api/v1/users/{id})
	GetUser(c *gin.Context, id string, params GetUserParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetUsers operation middleware
func (siw *ServerInterfaceWrapper) GetUsers(c *gin.Context) {

	c.Set(OidcScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUsers(c)
}

// GetUser operation middleware
func (siw *ServerInterfaceWrapper) GetUser(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(OidcScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUserParams

	// ------------- Optional query parameter "fields" -------------

	err = runtime.BindQueryParameter("form", true, false, "fields", c.Request.URL.Query(), &params.Fields)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter fields: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUser(c, id, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/api/v1/users", wrapper.GetUsers)
	router.GET(options.BaseURL+"/api/v1/users/:id", wrapper.GetUser)
}

type GetUsersRequestObject struct {
}

type GetUsersResponseObject interface {
	VisitGetUsersResponse(w http.ResponseWriter) error
}

type GetUsers200JSONResponse []User

func (response GetUsers200JSONResponse) VisitGetUsersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetUserRequestObject struct {
	Id     string `json:"id"`
	Params GetUserParams
}

type GetUserResponseObject interface {
	VisitGetUserResponse(w http.ResponseWriter) error
}

type GetUser200JSONResponse User

func (response GetUser200JSONResponse) VisitGetUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List users
	// (GET /api/v1/users)
	GetUsers(ctx context.Context, request GetUsersRequestObject) (GetUsersResponseObject, error)
	// Returns a user by ID
	// (GET /api/v1/users/{id})
	GetUser(ctx context.Context, request GetUserRequestObject) (GetUserResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetUsers operation middleware
func (sh *strictHandler) GetUsers(ctx *gin.Context) {
	var request GetUsersRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetUsers(ctx, request.(GetUsersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUsers")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetUsersResponseObject); ok {
		if err := validResponse.VisitGetUsersResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetUser operation middleware
func (sh *strictHandler) GetUser(ctx *gin.Context, id string, params GetUserParams) {
	var request GetUserRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetUser(ctx, request.(GetUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetUserResponseObject); ok {
		if err := validResponse.VisitGetUserResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}
